language: python
env:
  global:
    - PIP_CACHE_DIR="$HOME/.cache/pip"  # unify pip cache location for all platforms
cache:
  pip: true
  directories:
  - $HOME/.cache/pip
before_cache:
- rm -f $HOME/.cache/pip/log/debug.log
notifications:
  email: false
stages:
- check
- test
- name: deploy
  if: repo = casperdcl/argopt AND NOT type = pull_request
jobs:
  include:
  - stage: test
    name: py2.6
    python: 2.6
    env: TOXENV=py26
    dist: trusty
  - name: py2.7
    python: 2.7
    env: TOXENV=py27
  - name: py3.4
    python: 3.4
    env: TOXENV=py34
  - name: py3.5
    python: 3.5
    env: TOXENV=py35
  - name: py3.6
    python: 3.6
    env: TOXENV=py36
  - name: py3.7
    python: 3.7
    env: TOXENV=py37
  - name: pypy2.7
    python: pypy2.7-5.10.0
    env: TOXENV=pypy
  - name: pypy3.5
    python: pypy3.5-5.10.0
    env: TOXENV=pypy3
  - stage: check
    name: style
    python: 3.7
    env: TOXENV=flake8
  - name: setup
    python: 3.7
    env: TOXENV=setup.py
  - stage: deploy
    name: PyPI and GitHub
    python: 3.7
    install:
    script:
    - pip install .[dev]
    - make build
    - echo "$GPG_KEY" | base64 --decode > .key.gpg
    - gpg --import .key.gpg
    - rm .key.gpg
    - git log --pretty='format:- %s%n%b---' $(git tag --sort=creatordate | tail -n2 | head -n1)..HEAD > CHANGES.md
    deploy:
    - provider: script
      script: twine upload -s -i casper.dcl@physics.org dist/argopt-*
      skip_cleanup: true
      on:
        tags: true
    - provider: releases
      api_key: $GITHUB_TOKEN
      file_glob: true
      file: dist/argopt-*.whl*
      skip_cleanup: true
      draft: true
      name: argopt $TRAVIS_TAG stable
      edge: true
      tag_name: $TRAVIS_TAG
      target_commitish: $TRAVIS_COMMIT
      release_notes_file: CHANGES.md
      on:
        tags: true
before_install:
- git fetch --tags
install:
- pip install tox
- pip install .
script:
- tox
