# sudo: required
# dist: trusty
language: python
matrix:
  include:
  - python: 2.6
    env: TOXENV=py26
  - python: 2.7
    env: TOXENV=py27
  - python: 3.3
    env: TOXENV=py33
  - python: 3.4
    env: TOXENV=py34
  - python: 3.5
    env: TOXENV=py35
  - python: 3.6
    env: TOXENV=py36
  - python: 3.7-dev
    env: TOXENV=py37-dev
  - python: pypy2.7-5.8.0
    env: TOXENV=pypy
  - python: pypy3.5-5.8.0
    env: TOXENV=pypy3
  - python: 3.6
    env: TOXENV=flake8
cache:
  pip: true
  directories:
    - $HOME/.cache/pip
before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log
notifications:
  email: false
before_install:
  # fix a crash with multiprocessing on Travis
  # - sudo rm -rf /dev/shm
  # - sudo ln -s /run/shm /dev/shm
  # coverage submission packages
  - git fetch --tags
install:
  - pip install tox
  - python setup.py install
script:
  - tox
